defmodule ControlServerWeb.LiveHelpers do
  @moduledoc """
  Autogenerated module.
  """
  import Phoenix.LiveView.Helpers

  @doc """
  Renders a component inside the `ControlServerWeb.ModalComponent` component.

  The rendered modal receives a `:return_to` option to properly update
  the URL when the modal is closed.

  ## Examples

      <%= live_modal @socket, ControlServerWeb.KubeClusterLive.FormComponent,
        id: @kube_cluster.id || :new,
        action: @live_action,
        kube_cluster: @kube_cluster,
        return_to: Routes.kube_cluster_index_path(@socket, :index) %>
  """
  def live_modal(socket, component, opts) do
    path = Keyword.fetch!(opts, :return_to)
    modal_opts = [id: :modal, return_to: path, component: component, opts: opts]
    live_component(socket, ControlServerWeb.ModalComponent, modal_opts)
  end
end
