defmodule ControlServerWeb.PageLive do
  @moduledoc """
  Autogenerated.
  """
  use ControlServerWeb, :live_view

  @impl true
  @spec mount(any, any, Phoenix.LiveView.Socket.t()) :: {:ok, Phoenix.LiveView.Socket.t()}
  def mount(_params, _session, socket) do
    {:ok, socket |> assign(:running_set, %{monitoring: false})}
  end

  @impl true
  def handle_event("start_service", %{"service" => service_name}, socket) do
    {:noreply, assign(socket, :running_set, %{socket.assigns.running_set | service_name => true})}
  end

  @impl true
  def handle_event("stop_service", %{"service" => service_name}, socket) do
    {:noreply,
     assign(socket, :running_set, %{socket.assigns.running_set | service_name => false})}
  end
end
