---
name: 'Setup CI'
description: 'Sets up runner for CI'
inputs:
  bi_cache:
    description: 'Pull cached bi binary'
    default: 'false'
  elixir_cache:
    description: 'Set up Elixir cache'
    default: 'true'
  go_cache:
    description: 'Set up Go cache'
    default: 'true'
  reg_tool_cache:
    description: 'Pull cached registry-tool binary'
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Setup ASDF
      uses: ./.github/actions/setup-asdf

    - name: Determine bi cache key
      shell: bash
      if: ${{ inputs.bi_cache == 'true' }}
      run: |
        echo "BI_REVISION=$(bin/bix go bi-revision)" >> "$GITHUB_ENV"

    - name: Restore BI cache
      if: ${{ inputs.bi_cache == 'true' }}
      uses: actions/cache/restore@0400d5f644dc74513175e3cd8d07132dd4860809
      with:
        path: |
          /home/runner/.local/share/bi/dev/
        key: ${{ runner.os }}-bi-${{ env.BI_REVISION }}
        restore-keys: |
          ${{ runner.os }}-bi-

    - name: Restore elixir cache
      if: ${{ inputs.elixir_cache == 'true' }}
      uses: actions/cache/restore@0400d5f644dc74513175e3cd8d07132dd4860809
      id: elixir-cache
      with:
        path: |
          platform_umbrella/deps
          platform_umbrella/_build
          platform_umbrella/.dialyzer
        key:
          ${{ runner.os }}-ex-${{ hashFiles('**/mix.lock', '.tool-versions') }}
        restore-keys: |
          ${{ runner.os }}-ex-

    - name: Restore Go cache
      if: ${{ inputs.go_cache == 'true' }}
      uses: actions/cache/restore@0400d5f644dc74513175e3cd8d07132dd4860809
      with:
        path: |
          ${{ env.GOCACHE }}
          ${{ env.GOMODCACHE }}
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum', '.tool-versions') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Determine bi cache key
      shell: bash
      if: ${{ inputs.reg_tool_cache == 'true' }}
      run: |
        echo "REG_TOOL_REVISION=$(bin/bix go registry-tool-revision)" >> "$GITHUB_ENV"

    - name: Restore registry-tool cache
      if: ${{ inputs.reg_tool_cache == 'true' }}
      uses: actions/cache/restore@0400d5f644dc74513175e3cd8d07132dd4860809
      with:
        path: |
          /home/runner/.local/share/bi/registry-tool/
        key: ${{ runner.os }}-reg-tool-${{ env.REG_TOOL_REVISION }}
        restore-keys: |
          ${{ runner.os }}-reg-tool-
