name: 'Setup CI'
description: 'Sets up runner for CI'
inputs:
  go_cache:
    description: 'Set up Go cache'
    default: 'true'
  elixir_cache:
    description: 'Set up Elixir cache'
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: Setup ASDF
      uses: ./.github/actions/setup-asdf

    - name: Determine hash keys
      shell: bash
      run: bin/bix ci-gen-hashes >> "$GITHUB_ENV"

    - name: Restore elixir cache
      if: ${{ inputs.elixir_cache == 'true' }}
      uses: actions/cache/restore@v4
      id: elixir-cache
      with:
        path: |
          platform_umbrella/deps
          platform_umbrella/_build
          platform_umbrella/.dialyzer
          ~/.local/share/bi
        key: ${{ env.ELIXIR_HASH_KEY }}
        restore-keys: |
          ${{ runner.os }}-elixir-

    - name: Restore Go cache
      if: ${{ inputs.go_cache == 'true' }}
      uses: actions/cache/restore@v4
      with:
        path: |
          /home/runner/.cache/go-cache
          /home/runner/.cache/go-mod-cache
        key: ${{ env.GO_HASH_KEY }}
        restore-keys: |
          ${{ runner.os }}-go-

    - shell: bash
      run: rm -f bi_revision.txt
