name: 'Setup CI'
description: 'Sets up runner for CI'
inputs:
  go_cache:
    description: 'Set up Go cache'
    default: 'true'
  elixir_cache:
    description: 'Set up Elixir cache'
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: Setup ASDF
      uses: ./.github/actions/setup-asdf

    - name: Restore elixir cache
      if: ${{ inputs.elixir_cache == 'true' }}
      uses: actions/cache/restore@v4
      id: elixir-cache
      with:
        path: |
          platform_umbrella/deps
          platform_umbrella/_build
          platform_umbrella/.dialyzer
        key:
          ${{ runner.os }}-ex-${{ hashFiles('**/mix.lock', '.tool-versions') }}
        restore-keys: |
          ${{ runner.os }}-ex-

    - name: Restore Go cache
      if: ${{ inputs.go_cache == 'true' }}
      uses: actions/cache/restore@v4
      with:
        path: |
          ${{ env.GOCACHE }}
          ${{ env.GOMODCACHE }}
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum', '.tool-versions') }}
        restore-keys: |
          ${{ runner.os }}-go-
