defmodule ServerWeb.PageLive do
  @moduledoc """
  Autogenerated.
  """
  use ServerWeb, :live_view
  alias Server.Configs.RunningSet

  @impl true
  @spec mount(any, any, Phoenix.LiveView.Socket.t()) :: {:ok, Phoenix.LiveView.Socket.t()}
  def mount(_params, _session, socket) do
    {:ok, socket |> assign(:running_set, RunningSet.get!())}
  end

  @impl true
  def handle_event("start_service", %{"service" => service_name}, socket) do
    {:ok, new_config} =
      socket.assigns.running_set
      |> RunningSet.set_running(service_name)

    {:noreply, assign(socket, :running_set, new_config)}
  end

  @impl true
  def handle_event("stop_service", %{"service" => service_name}, socket) do
    {:ok, new_config} =
      socket.assigns.running_set
      |> RunningSet.set_running(service_name, false)

    {:noreply, assign(socket, :running_set, new_config)}
  end
end
