---
name: 'Setup ASDF'
description: 'Sets up ASDF'
runs:
  using: 'composite'
  steps:
    - name: Install ASDF CLI
      uses: asdf-vm/actions/install@1902764435ca0dd2f3388eea723a4f92a4eb8302 # v4
      with:
        skip_install: true

    - name: Restore ASDF cache
      uses: actions/cache/restore@v4
      id: asdf-cache
      with:
        # https://github.com/asdf-vm/asdf/blob/master/.gitignore
        path: |
          ~/.asdf/installs
          ~/.asdf/plugins
          ~/.asdf/shims
        key: ${{ runner.os }}-asdf-${{ hashFiles('.tool-versions') }}
        restore-keys: ${{ runner.os }}-asdf-

    - name: Install ASDF Tools
      uses: asdf-vm/actions/install@1902764435ca0dd2f3388eea723a4f92a4eb8302 # v4
      # See https://github.com/asdf-vm/actions/issues/445
      if: ${{ steps.asdf-cache.outputs.cache-hit != 'true' }}

    - name: Reshim ASDF
      shell: bash
      run: asdf reshim
