---
name: 'Setup ASDF'
description: 'Sets up ASDF'
inputs:
  asdf_version:
    description: 'ASDF version to use'
    required: true
    default: '0.18.0'
runs:
  using: 'composite'
  steps:
    - name: Install ASDF CLI
      uses: asdf-vm/actions/setup@1902764435ca0dd2f3388eea723a4f92a4eb8302 # v4
      with:
        asdf_version: ${{ inputs.asdf_version }}

    - name: Restore ASDF cache
      uses: actions/cache/restore@0400d5f644dc74513175e3cd8d07132dd4860809
      id: asdf-cache
      with:
        # https://github.com/asdf-vm/asdf/blob/master/.gitignore
        path: |
          ~/.asdf/installs
          ~/.asdf/plugins
          ~/.asdf/shims
        key: ${{ runner.os }}-asdf-${{ hashFiles('.tool-versions') }}
        restore-keys: ${{ runner.os }}-asdf-

    - name: Install ASDF Tools
      uses: asdf-vm/actions/install@1902764435ca0dd2f3388eea723a4f92a4eb8302 # v4
      # See https://github.com/asdf-vm/actions/issues/445
      if: ${{ steps.asdf-cache.outputs.cache-hit != 'true' }}
      with:
        asdf_version: ${{ inputs.asdf_version }}
        skip_install: true

    - name: Reshim ASDF
      shell: bash
      run: asdf reshim
