defmodule CommonCore.Defaults.Images do
  @moduledoc false
  @cert_manager_image_tag "v1.14.7"
  @kiali_image_version "v1.86.1"

  def cert_manager_image_version, do: @cert_manager_image_tag
  def vm_cluster_tag, do: "v1.93.9-cluster"
  def vm_tag, do: "v1.93.9"
  def kiali_image_version, do: @kiali_image_version

  def addon_resizer_image, do: "registry.k8s.io/autoscaling/addon-resizer:1.8.22"
  def alertmanager_image, do: "quay.io/prometheus/alertmanager:v0.27.0"
  def aws_load_balancer_controller_image, do: "public.ecr.aws/eks/aws-load-balancer-controller:v2.8.1"
  def bootstrap_image, do: "public.ecr.aws/batteries-included/kube-bootstrap:latest"
  def cert_manager_acmesolver_image, do: "quay.io/jetstack/cert-manager-acmesolver:#{cert_manager_image_version()}"
  def cert_manager_cainjector_image, do: "quay.io/jetstack/cert-manager-cainjector:#{cert_manager_image_version()}"
  def cert_manager_controller_image, do: "quay.io/jetstack/cert-manager-controller:#{cert_manager_image_version()}"
  def cert_manager_ctl_image, do: "quay.io/jetstack/cert-manager-ctl:#{cert_manager_image_version()}"
  def cert_manager_webhook_image, do: "quay.io/jetstack/cert-manager-webhook:#{cert_manager_image_version()}"
  def cloudnative_pg_image, do: "ghcr.io/cloudnative-pg/cloudnative-pg:1.23.2"
  def control_server_image, do: "public.ecr.aws/batteries-included/control-server:latest"
  def ferretdb_image, do: "ghcr.io/ferretdb/ferretdb:1.22.0"
  def forgejo_image, do: "codeberg.org/forgejo/forgejo:1.21.11-2"
  def frrouting_frr_image, do: "quay.io/frrouting/frr:8.5.4"
  def grafana_image, do: "grafana/grafana:10.4.5"
  def istio_pilot_image, do: "docker.io/istio/pilot:1.22.1-distroless"
  def istio_proxy_image, do: "docker.io/istio/proxyv2:1.22.1-distroless"
  def karpenter_image, do: "public.ecr.aws/karpenter/controller:0.37.0"
  def keycloak_image, do: "quay.io/keycloak/keycloak:24.0.5"
  def kiali_image, do: "quay.io/kiali/kiali:#{kiali_image_version()}"
  def kiwigrid_sidecar_image, do: "quay.io/kiwigrid/k8s-sidecar:1.27.4"
  def kube_state_metrics_image, do: "registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.12.0"
  def loki_image, do: "grafana/loki:2.9.8"
  def metallb_controller_image, do: "quay.io/metallb/controller:v0.13.12"
  def metallb_speaker_image, do: "quay.io/metallb/speaker:v0.13.12"
  def metrics_server_image, do: "registry.k8s.io/metrics-server/metrics-server:v0.7.1"
  def node_exporter_image, do: "quay.io/prometheus/node-exporter:v1.8.1"
  def oauth2_proxy_image, do: "quay.io/oauth2-proxy/oauth2-proxy:v7.6.0"
  def promtail_image, do: "grafana/promtail:2.9.8"
  def redis_operator_image, do: "quay.io/spotahome/redis-operator:v1.2.4"
  def smtp4dev_image, do: "rnwood/smtp4dev:3.1.4"
  def text_generation_webui_image, do: "atinoda/text-generation-webui:default-snapshot-2023-12-10"
  def trivy_operator_image, do: "ghcr.io/aquasecurity/trivy-operator:0.21.3"
  def aqua_node_collector, do: "ghcr.io/aquasecurity/node-collector:0.2.1"
  def aqua_trivy_checks, do: "ghcr.io/aquasecurity/trivy-checks:0.13.0"

  def trust_manager_image, do: "quay.io/jetstack/trust-manager:v0.11.0"
  def trust_manager_init_image, do: "quay.io/jetstack/cert-manager-package-debian:20210119.0"
  def vm_operator_image, do: "victoriametrics/operator:v0.44.0"

  def knative_serving_queue_image, do: "gcr.io/knative-releases/knative.dev/serving/cmd/queue:v1.14.1"
  def knative_serving_activator_image, do: "gcr.io/knative-releases/knative.dev/serving/cmd/activator:v1.14.1"
  def knative_serving_autoscaler_image, do: "gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler:v1.14.1"
  def knative_serving_controller_image, do: "gcr.io/knative-releases/knative.dev/serving/cmd/controller:v1.14.1"
  def knative_serving_webhook_image, do: "gcr.io/knative-releases/knative.dev/serving/cmd/webhook:v1.14.1"

  def knative_istio_controller_image, do: "gcr.io/knative-releases/knative.dev/net-istio/cmd/controller:v1.14.1"
  def knative_istio_webhook_image, do: "gcr.io/knative-releases/knative.dev/net-istio/cmd/webhook:v1.14.1"
end
