---
name: Dependabot auto-merge
'on': pull_request

permissions:
  contents: read
  pull-requests: read

jobs:
  dependabot:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    steps:
      - name: Get app token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2
        id: app-token
        with:
          app-id: ${{ vars.DEPENDABOT_APP_ID }}
          private-key: ${{ secrets.DEPENDABOT_PRIVATE_KEY }}

      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@08eff52bf64351f401fb50d4972fa95b9f2c2d1b # v2
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Enable auto-merge for Dependabot PRs
        if:
          ${{ steps.metadata.outputs.update-type !=
          'version-update:semver-major' }}
        run: |
          echo "$APP_TOKEN" | gh auth login --with-token
          gh pr merge --auto --squash "$PR_URL"
        env:
          APP_TOKEN: ${{ steps.app-token.outputs.token }}
          PR_URL: ${{github.event.pull_request.html_url}}
