---
name: Build and push Keycloak image

on:
  workflow_dispatch:
    inputs:
      version:
        description: The upstream version of Keycloak to build from
        required: true
        type: string

permissions:
  id-token: write
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3

      - name: Login to GHCR
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          context: .
          file: docker/keycloak.dockerfile
          push: true
          tags: ghcr.io/batteries-included/keycloak:${{ inputs.version }}
          build-args: |
            KC_VERSION=${{ inputs.version }}
