---
name: 'Keycloak Trigger Missing From Upstream'

'on':
  schedule:
    - cron: '15 8 * * *'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  check_upstream:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4
        with:
          persist-credentials: false

      - name: Setup ASDF
        uses: ./.github/actions/setup-asdf

      - name: Kick off keycloak workflow for missing tags
        env:
          GH_TOKEN: ${{ github.token }}
        run: bin/bix keycloak trigger-missing-upstream
