---
name: Build and push Keycloak image

'on':
  workflow_dispatch:
    inputs:
      version:
        description: The upstream version of Keycloak to build from
        required: true
        type: string

permissions:
  id-token: write
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4
        with:
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3

      - name: Login to GHCR
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup ASDF
        uses: ./.github/actions/setup-asdf

      - name: Build keycloak image
        run: bin/bix docker build-image keycloak ${{ inputs.version }}

      - name: Push keycloak image
        run: bin/bix keycloak push-keycloak ${{ inputs.version }}
