---
name: 'Check keycloak versions'

'on':
  schedule:
    - cron: '15 8 * * *'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  check_upstream:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false

      - name: Setup ASDF
        uses: ./.github/actions/setup-asdf

      - name: Kick off keycloak workflow for missing tags
        run: |
          for tag in $(echo \
            "$(yq '.keycloak_upstream.tags[]' image_registry.yaml)" \
            "$(yq '.keycloak.tags[]' image_registry.yaml)"  | \
          tr ' ' '\n' | \
          sort | \
          uniq -u); do
            gh workflow run "keycloak.yml" -f "version=${tag}"
          done
